PL_TEAMS = [
    "All Teams",
    "Arsenal",
    "Aston Villa",
    "Brentford",
    "Burnley",
    "Brighton",
    "Chelsea",
    "Crystal Palace",
    "Everton",
    "Leeds",
    "Leicester",
    "Liverpool",
    "Man City",
    "Man United",
    "Newcastle",
    "Norwich",
    "Southampton",
    "Tottenham",
    "Watford",
    "West Ham",
    "Wolves",
]